version: "3.7"

services:
    db:
        image: postgres:9.6.17-alpine
        container_name: psql-container
        environment: 
            POSTGRES_USER: backendchallenge
            POSTGRES_PASSWORD: backendchallenge
    app:
        working_dir: /usr/app
        entrypoint: ["/bin/bash", "./docker-entrypoint.sh"]
        image: node:10-slim
        container_name: backendchallenge
        ports:
            - "4000:4000"
        env_file:
            - .env
        volumes: 
            - .:/usr/app
        depends_on:
            - db
